Add translations system
calidae/systelab-pages pull request #1
Opened 2017-12-15 14:40 UTC by afontcu

A falta de tenir el contingut definitiu.

2017-12-15 15:03 UTC, xevops requested changes

2017-12-15 15:03 UTC, xevops commented on launcher/index.html
> +            <span class="trn">es el sistema de información para el laboratorio sin papeles</span>.
Aquesta traducció no funciona pq el punt i final està fora del span que gestiona la traducció. Caldria treure el punt de la traducció

2017-12-15 15:08 UTC, afontcu commented on launcher/index.html
> +            <span class="trn">es el sistema de información para el laboratorio sin papeles</span>.
cooorrecto! resolt. thanks

2017-12-15 15:13 UTC, xevops approved these changes

2017-12-18 09:01 UTC, oriolfg approved these changes

2017-12-18 09:09 UTC, merged